### ISSUE TITLE
Latest apache expoerter giving error

### ISSUE THREAD

**Issue by gopukrishnantec** [bitnami/bitnami-docker-apache-exporter#1]
When using the latest apache exporter in openshift, giving below error : 
apache_exporter: error: unknown short flag '-s', try --help

Image: bitnami/apache-exporter:latest
Command: apache_exporter -scrape_uri http://application:7520/server-status/?auto

It looks like the latest image is having some changes which is causing the error.

OpenShift Master: v3.11.153
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.153

**Comment by Mauraza** [comment]
Hi @gongomgra,

apache-exporter was updated now `-scape_uri` is `--scape_uri`. So change the command  `apache_exporter -scrape_uri http://application:7520/server-status/?auto` to Command: `apache_exporter --scrape_uri http://application:7520/server-status/?auto`.

I hope that work!

**Comment by gopukrishnantec** [comment]
Hi @Mauraza 
It worked! Thank you so much.
PS: you used tagged wrong user :)

Thanks and be safe
